# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-20.04']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build-DB
        run: docker-compose build
      - name: Create-DB
        run: docker-compose up -d
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U root; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Test
        run: go test -v main_test.go

  build:
    runs-on: ${{ matrix.os }}
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: go build -v main.go

