# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI
on: 
  push: 
    branches: ['*']
  pull_request: 
    branches: ['*']

jobs:
  test:
    runs-on: self-hosted
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build-DB
        run: docker-compose build
      - name: Create-DB
        run: docker-compose up -d
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U root; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Test
        run: go test -v main_test.go

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: go build -v main.go
                 
                  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
    # Artifact name
         name: programa
    # A file, directory or wildcard pattern that describes what to upload
        path: main
  
           docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
    

  


